### ISSUE TITLE
Napraviti dijagram aktivnosti

### ISSUE THREAD

**Issue by marioolcar** [marioolcar/BADELPADEL#6]

**Comment by JCukrov** [comment]
Napravio sam generalno kako bi to trebalo izgledati. Nisam jedino presiguran oko izgleda dijagrama kad ima više mogućih aktivnosti pa sam ih odlučio raščlanit na njih više.

Mislim da je dijagram za rezervaciju turnira više-manje dobar, a što se tiče turnira nisam prezadovoljan sa izgledom krajnjeg djela gdje se rastavlja na otvorene i odigrane turnire. Također, za turnire sam razmišljao i dodat stupac za organizatora turnira koji bi mogao onda odobriti prijave, ali opet nisam pretjerano siguran kako bi to trebalo izgledat.
Dolje ima slikica kak sad izgleda zasad, rađe bi dobio povratnu informaciju prije nego pusham.

![Dijagram aktivnosti - turniri](https://github.com/user-attachments/assets/9c1fdf8d-1654-4a2f-a517-8cb22b0b839d)
![Dijagram aktivnosti - rezervacija termina](https://github.com/user-attachments/assets/93e5d3e5-e288-407e-9fb9-ce9a73996f6d)
